---
project_name: CD45pCD3p
# it can even be a CSV file like the one in a Cell Ranger aggregation
input_expression: "/home/kmlanderos/large/pbtumor-all/raw/cellranger/aggr/CD45pCD3p"
# A table of the metadata per library, or the whole metadata ready
# it can be multiple file
metadata:
  - "/home/kmlanderos/pbtumor-all/info/metadata_library.csv"
  - "/home/kmlanderos/large/pbtumor-all/results/ab_demux/cd3x/CD45pCD3p.rds"
# if you don't add "/" at the end, it will append 'project_name'
output_dir: "/home/kmlanderos/large/pbtumor-all/results/quality_control/"
# A file will sufice; columns must be metrics names in the metadata
filtering:
  file: "./data/file.csv"
  nFeature_RNA: [300, 3000, 1]
  nCount_RNA: [500, 9000, 1]
  percent.mt: [-Inf, 10, 1]
  expr: "!orig.HT_ID.global %in% c('Doublet', 'Negative')"
...
